# Generated by Django 5.0 on 2023-12-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
