# Generated by Django 5.0 on 2023-12-11 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_visitas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='likes',
            field=models.ManyToManyField(related_name='not_megustas', to=settings.AUTH_USER_MODEL),
        ),
    ]
