# Generated by Django 5.0 on 2023-12-11 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_noticia_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='not_megustas', to=settings.AUTH_USER_MODEL),
        ),
    ]
