# Generated by Django 5.0 on 2023-12-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('razon', models.CharField(choices=[('problemas_tecnicos', 'Problemas técnicos'), ('sugerencias', 'Sugerencias'), ('publicidad', 'Publicidad')], default='problemas_tecnicos', max_length=20)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
