# Generated by Django 5.0 on 2023-12-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='razon',
            field=models.CharField(choices=[('problemas_tecnicos', 'Problemas técnicos'), ('sugerencias', 'Sugerencias'), ('publicidad', 'Publicidad'), ('reportar', 'Reportar Usuario/Post')], default='problemas_tecnicos', max_length=20),
        ),
    ]
