# Generated by Django 5.0 on 2023-12-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(default='usuarios/default.png', upload_to='usuarios/'),
        ),
    ]
